### ISSUE TITLE
Question about setsar (NTSC v. PAL)

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#167]
hi all,

I'm not sure exactly where to begin, but I recently received some FFV1/MKVs from a vendor, a bunch of which failed mediaconch's FFV1 implementation checker. Specifically, the fail had something to do with sar_den:

![screen shot 2017-08-04 at 11 40 40 am](https://user-images.githubusercontent.com/8987230/29043487-66814bd4-7b89-11e7-9ae6-476d5c96cd86.png)

In trying to figure out the source of the problem, and a potential solution, I began looking into ways for the vendor to more explicitly set the sar and dar during the transcode (vendor workflow is v210/mov to ffv1/mkv). Looking at vrecord, I noticed that it sets the setsar (whoa) at 40/27 for both NTSC and PAL. I guess my question is: is this correct? Anything par-, dar-, or sar-related makes me wanna scream, so I apologize if I'm completely wrong, but it seems to me that (1) vrecord is thinking "storage aspect ratio," while ffmpeg is thinking "sample aspect ratio," and (2) 40/27 should only be for NTSC, right? Shouldn't PAL be 5/4? See this table I pulled from somewhere:

![math-table](https://user-images.githubusercontent.com/8987230/29044379-28713b3e-7b8d-11e7-8276-5f3a8e8070e6.png)

Again, sorry if this is wordy or annoying. Any thoughts/help would be greatly appreciated. 

Ben

**Comment by kieranjol** [comment]
Hi Ben,

I can only really speak for PAL. For PAL, 5:4 is the Storage aspect ratio, as in 720/576=5/4 aka 1.25:1.
The PAR (or as ffmpeg calls it, the Sample Aspect Ratio) should be 16:15 in order to display 720 as 768 (you might see 59:54 if the width is 704).
Anyhow, I think I wrote that inital code back when I didn't know much and I found that copy pasting the NTSC code just worked - it produced a DAR of 4/3.
I should look into it deeper, but it seems that the `setdar` value of 4.3 overrides the 40/27 `setsar` value. Either way, it should be altered to be 16:15.

Anyhow, I don't think this is the issue here. Can you post the full mediaconch implementation check output?

**Comment by ablwr** [comment]
Yeah where is your MediaConch issue?

**Comment by kieranjol** [comment]
I sent a pull request there: https://github.com/amiaopensource/vrecord/issues/167
But I think that this is less of an issue of 'what value is the SAR/DAR', and more 'where is the SAR/DAR info stored in Matroska and how is Mediaconch validating this against the standard'. So this is probably more of a mediaconch issue.

**Comment by bturkus** [comment]
closing...thanks for the help/info all!
