### ISSUE TITLE
Broadcast Range Pixels not highlighting

### ISSUE THREAD

**Issue by iamdamosuzuki** [amiaopensource/vrecord#169]
Using version 2017-07-27

Full Range pixels are highlighting properly, but Broadcast Range pixels are not. 

![screen shot 2017-08-08 at 4 03 04 pm](https://user-images.githubusercontent.com/3967767/29098438-3ace1d3e-7c54-11e7-81fd-15b29724caab.png)
![screen shot 2017-08-08 at 4 03 18 pm](https://user-images.githubusercontent.com/3967767/29098440-3cf3bbc8-7c54-11e7-8e4f-d58a25863c1d.png)

**Comment by retokromer** [comment]
@iamdamosuzuki By chance, can you name me correct working version? The last two releases were «only» documentations improvements and a test if FFmpeg is correctly installed… Otherwise I will delve into the commit.

**Comment by iamdamosuzuki** [comment]
It's working fine on this version:

`vrecord 0.7.28`

Here's a screenshot

![screen shot 2017-08-11 at 5 07 45 pm](https://user-images.githubusercontent.com/3967767/29235822-8b83ee06-7eb7-11e7-8f41-d92a74c0d11a.png)

**Comment by retokromer** [comment]
@iamdamosuzuki Thank you!

**Comment by retokromer** [comment]
Hmm…

I cannot test with a setting those days, but reading the code, the only [differences](https://github.com/amiaopensource/vrecord/compare/v0.7.28...v2017-07-27) I can see between `0.7.28` and `2017-07-27` (or the current `HEAD`) are:

- add [`-color_range jpeg`](https://github.com/amiaopensource/vrecord/commit/f84e75950ae5422e497eba2e3c80ddcb38bcba17) for full range, instead of `-color_range mpeg` in all the other cases;
- modify the [playbackfilter](https://github.com/amiaopensource/vrecord/commit/99df0d65a3b37798a3ebf7483a1ea1eecb3c2682) for the `Visual + Numerical` case;
- add a [playbackfilter](https://github.com/amiaopensource/vrecord/commit/1e52a68c4e7960ed41e63718bd73fc71667c04bc) for the new `Bit Planes` case.

Yet no one of these seems to me related to this bug… or am I missing something? Any thoughts @dericed @privatezero and/or @savcampbell? Thanks!

**Comment by dericed** [comment]
From the waveform in the sample image it seems like the pluge is set too high and so that the samples of the waveform are all within broadcast range within 16-235, thus the broadcast range viewer should not have to highlight everything. @iamdamosuzuki could you try 0.7.28 again with an out of range source or is ffmpeg somewhere now constraining the input to broadcast range?

**Comment by retokromer** [comment]
@iamdamosuzuki Could you possibly also test with this [commit](https://github.com/amiaopensource/vrecord/pull/172/commits/754916fad651504e03272a85727bb49c3129c678)? Thank you!

**Comment by iamdamosuzuki** [comment]
I made a more extreme example and tested with 2017-07-27

First, this is a screenshot of test bars with the Luma cranked up, the Black cranked down and the Broadcast Range Visual option selected. It looks like in this configuration the waveform is clipped so that nothing actually exceeds broadcast range. in this case it makes sense that nothing is highlighted, because nothing is exceeding broadcast range values. Am I correct in believing that this is not the expected behavior? Shouldn't it be allowing the waveform to exceed broadcast range, but highlighting the pixels that exceed the value?

![broadcastrange](https://user-images.githubusercontent.com/3967767/29296178-77633e60-810d-11e7-9a6f-205afad3e49a.png)

This next screenshot is the same bars, but with Full Range Visual selected. We're seeing the same thing here, but with highlighting. The waveform is clipped at broadcast range, not full-range, but the clipped pixels are highlighted. 

![fullrange](https://user-images.githubusercontent.com/3967767/29296187-879c256c-810d-11e7-9a53-93b50607000a.png)

**Comment by iamdamosuzuki** [comment]
upon @dericed 's  request I recorded with both of these settings. The resulting video files were clipped at the broadcast range values. I've attached the QCTools reports for both so you can take a look:

[BoadcastRange_Test.mov.qctools.xml.gz](https://github.com/amiaopensource/vrecord/files/1223765/BoadcastRange_Test.mov.qctools.xml.gz)
[FullRange_Test.mov.qctools.xml.gz](https://github.com/amiaopensource/vrecord/files/1223766/FullRange_Test.mov.qctools.xml.gz)

**Comment by MIAPtech** [comment]
the highlighting pattern here is consistent with what I observed in issue #173 - the "Full Range Visual" mode highlighting pixels right at broadcast limits (16 and 235) and only at those values

I made that a separate issue because I am not able to replicate the hard clipping here - I can get values on the waveform under 16 and over 235 (which are highlighted in "Broadcast Range Visual", not highlighted in "Full Range Visual"). Is this possibly a hardware issue? Seems like maybe the signal is being clipped at broadcast levels before it even gets to the vrecord waveform?

**Comment by iamdamosuzuki** [comment]
It appears that the clipping is happening before vrecord, and is being caused by a BlackMagic Analog to SDI Mini Converter box. What a drag! But at least this ticket can be closed.

**Comment by retokromer** [comment]
I am a little confused. Why is there a different output from `vrecord 0.7.28` and `vrecord 2017-07-27` while using the same hardware? I would expect that the Mini Converter box produces the same, wrongly clipped output. But I cannot test it now.

**Comment by retokromer** [comment]
>Why is there a different output from `vrecord 0.7.28` and `vrecord 2017-07-27` while using the same hardware?

I’m still confused by this. Yet I’m closing this issue, because the Mini Converters seem to always clip the signal at broadcast levels.

**Comment by iamdamosuzuki** [comment]
I just found a forum post related to this topic. BMD doesn't seem to want to address this issue :-< 
http://forum.blackmagicdesign.com/viewtopic.php?f=18&t=7096

**Comment by BleakleyMcD** [comment]
Doesn't that forum end in a happy customer with BMD resolving their issue? Or I am confused. Has anyone used the Converter Utility software?

**Comment by iamdamosuzuki** [comment]
@BleakleyMcD the post is unfortunately for the SDI to HDMI converter. That option is greyed out when using Analog to SDI.

**Comment by BleakleyMcD** [comment]
Ah bummer! Tell 'em to fix it!

**Comment by BleakleyMcD** [comment]
BMD, that is.
