### ISSUE TITLE
Add volumedetect reporting

### ISSUE THREAD

**Issue by epiil** [amiaopensource/vrecord#23]
To bulk up audio QC, I wonder if it's worth incorporating ffmpeg's volumedetect reporting into one of the logs. 

Volumedetect filter info here:

http://ffmpeg.org/ffmpeg-filters.html#volumedetect

Here's an example of volumedetect reporting on an internally-generated 1kHz tone from a Sony J30 VTR (~ -20dB reading):

[Parsed_volumedetect_0 @ 0x7f98cbd00200] n_samples: 138334
[Parsed_volumedetect_0 @ 0x7f98cbd00200] mean_volume: -23.5 dB
[Parsed_volumedetect_0 @ 0x7f98cbd00200] max_volume: -20.1 dB
[Parsed_volumedetect_0 @ 0x7f98cbd00200] histogram_20db: 28700

**Comment by privatezero** [comment]
I just added a function to add peak dB information to the capture log (when qctools output is selected).  I'll keep investigating how to capture more info!

**Comment by retokromer** [comment]
What is the status of this issue?

**Comment by dericed** [comment]
open :-P

**Comment by privatezero** [comment]
There is some volume information logged (such as here https://github.com/amiaopensource/vrecord/blob/master/vrecord#L1272) but currently it is tied into the qctools report output as opposed to the volumedetect filter.

At one point I had a branch I was testing that forked the capture stream into volumedetect, but since the information is already being captured via qctools it seemed an unnecessary complication to add to the capture chain.

**Comment by epiil** [comment]
@privatezero many thanks for adding peak dB reportage. As QCTools and vrecord have seen improved audio monitoring since this ticket was written, kindly close at your discretion.

**Comment by retokromer** [comment]
Thank you very much, @epiil and @privatezero, for the information – and kudos to @privatezero for continuous improvements of that various open-source tools!
