### ISSUE TITLE
Request - Expand compadibility beyond BlackMagic capture cards/devices/drivers

### ISSUE THREAD

**Issue by drodz11** [amiaopensource/vrecord#238]
After first learning about preservation projects using VRecord at the most recent AMIA Conference, I was excited to return to my organization (Florida State University Libraries) with the hopes of trying it out myself. Upon taking a look at the documentation, I found that both I and FSU lacked the BlackMagic hardware to run the software. Although I may be able to secure funding to acquire this equipment at some point in the future, I imagine others like me may find (or have found) themselves in a similar situation.

In future versions, it would be fantastic to see an expansion of hardware compatibilities. I, for instance, have been using a Canopus ADVC55 for basic capture via Final Cut Pro for years, and I think many other individuals and smaller organizations are using similar kinds of hardware and would benefit from being able to do so with VRecord.

**Comment by dericed** [comment]
Hi @drodz11, the Canopus ADVC55 is lossy device that converts the incoming analog video into DV25. It could be possible to modify vrecord to support this by adding a condition to switch vrecord between the decklink input device and the iec61883 input device. I think this would be worthwhile for capturing DV tape, but it might not be recommended for analog capture since the capture card would be encoding to a lossy DV encoding. In that case it wouldn't be worthwhile to record to ffv1, j2k, or uncompressed but rather to write the DV encoding from the card as is to a file.

**Comment by retokromer** [comment]
An [Intensity Shuttle for USB 3.0](https://www.blackmagicdesign.com/products/intensity) costs USD 199.

It was possible, with a previous version (many improvements were recently made and I didn’t try again since), to run a modified `vrecord` with AJA hardware as well. However, it seems there are some legal issues when using their SDK.

**Comment by drodz11** [comment]
@retokromer @dericed Thanks for your responses. I hadn't considered the lossyness of the Canopus device within the encoding framework of VRecord, so that certainly makes sense. I am hoping I can secure some funding for an Intensity Shuttle as well (sometimes harder than it would seem, of course, even at such a cost). All the same, looking forward to seeing how hardware compatibility evolves and hopefully being able to use the software as it is now.

**Comment by dericed** [comment]
closing. vrecord can work with either piped input or via libavdevice, so compatibility efforts should be focused on those projects.

**Comment by retokromer** [comment]
Indeed! vrecord can work with other devices as well.
