### ISSUE TITLE
split field view?

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#279]
Hi,
A recent AMIA-L thread got me thinking about the possibility of adding a split field view to vrecord. How difficult would this be, on a scale 1-10 (keep in mind my skillz are prob a 1-2)?

Related question about process: would it makes the most sense to add this sort of thing to qcview.lua?

Thanks,
Ben

**Comment by privatezero** [comment]
Hi @bturkus! Personally I think that would make a lot of sense to add as part of the lua script so that people could switch to it on the fly if they ran into problems and wanted to immediately see if there was a difference across fields.

I have never worked with this filter, but there is a [separatefields](https://ffmpeg.org/ffmpeg-filters.html#separatefields-1) filter in ffmpeg. I imagine someone who worked with qctools could tell you what they used to work that magic in there?

**Comment by richardpl** [comment]
__separatefields__ will split fields into sequential frames. If you want both fields to appear at same time, use __il__ filter.

**Comment by aeschweik** [comment]
Hi, this is a great idea and I can work on adding it into the Lua script (where I also think it fits)!

**Comment by bturkus** [comment]
That'd be incredible! Thanks everyone!

**Comment by aeschweik** [comment]
First pass at this in #281, with documentation updates in the works!
