### ISSUE TITLE
[wish] make `vtest` optional

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/vrecord#334]
I suggest to make `vtest` optional when installing `vrecord`, because not each user does need it.

See [this commit](https://github.com/amiaopensource/homebrew-amiaos/pull/104/commits/af6abb43076ca064256a4214323b59a88b458a54) for a possible implementation. The following line should be added to the formula:
```rb
man1.install "vtest.1" if build.with? "vtest"
```

**Comment by retokromer** [comment]
I also suggest to implement in the formula the option to install the documentation. This allows users with bad internet connection to easily access to the documentation whenever needed.

**Comment by dericed** [comment]
vtest is only 18,594 bytes and requires less than a hundredth of a second to install. I'd prefer to leave the installation as-is, or possibly have an --dont-install-vtest-because-although-i-digitize-lossless-video-i-dont-have-18k-to-spare option.

Additionally the current test in vrecord.rb doesn't do any substantial testing of the vrecord installation, vtest may ultimately be useful to resolve this.

**Comment by retokromer** [comment]
Oh, it’s not at all a question of bytes or of milliseconds (I’m not that stupid), but of having a clean computer…
