### ISSUE TITLE
Error Message in ffmpeg_decklink_input.log: av_interleaved_write_frame(): Broken pipe

### ISSUE THREAD

**Issue by drodz11** [amiaopensource/vrecord#340]
Hello!

I am seeing the following error message at the end of my decklink input logs when capturing from VHS:

`av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
frame= 4504 fps= 30 q=-0.0 Lq=-0.0 q=-1.0 size= 1283035kB time=00:02:30.28 bitrate=69938.6kbits/s speed=   1x    
video:7397086kB audio:154970kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!`

The resulting captured video looks/sounds fine but was curious if this was message pointed to another non-visible issue or to some error I'm making in configuring and/or capturing. Any insight appreciated!

**Comment by dericed** [comment]
I suspect this happens when you stop vrecord by closing the playback window. When you stop vrecord in this way (by closing ffplay or mpv) it sends a SIG_PIPE signal to ffmpeg to stop. Then ffmpeg stops reading the input and works to finalize the output file and stop. Thus ffmpeg is receiving a partial frame as input which can't be written to the output and that's what I think it's complaining about. If you stop vrecord by setting a recording duration instead then you shouldn't see the error, otherwise by closing the playback window there will be a partial frame discrepancy between the input and output since ffmpeg is being stopped in the middle of reading an input frame.

**Comment by drodz11** [comment]
@dericed , I thought it might be something like that but wanted to confirm. Thanks very much!

**Comment by dericed** [comment]
But to be sure, was the file you created about 2:30 long?

**Comment by drodz11** [comment]
@dericed , Yes, I am currently putting together a proposal for my institution to enhance our digitization programs/services and creating some test captures and metadata reports, so I created a few short clips (~2:30) captured from VHS. A colleague noticed the error reports and I just wanted to be able to explain them.

**Comment by dericed** [comment]
Might be worthwhile to keep the issue open regarding the need to add an explanation of that error to the documentation.

**Comment by matigumma** [comment]
> I suspect this happens when you stop vrecord by closing the playback window. When you stop vrecord in this way (by closing ffplay or mpv) it sends a SIG_PIPE signal to ffmpeg to stop. Then ffmpeg stops reading the input and works to finalize the output file and stop. Thus ffmpeg is receiving a partial frame as input which can't be written to the output and that's what I think it's complaining about. If you stop vrecord by setting a recording duration instead then you shouldn't see the error, otherwise by closing the playback window there will be a partial frame discrepancy between the input and output since ffmpeg is being stopped in the middle of reading an input frame.

Hi, i think this is just what happen...
can i ask how to prevent it ?

**Comment by dericed** [comment]
Hi @matigumma, You could prevent it by declaring a duration at which to end the recording. Otherwise the way vrecord is designed, it ends the recording when the playback window is closed, this subsequently sends a SIG_PIPE signal to ffmpeg to stop it which causes the error message you see, but at the moment that's the intentional way that vrecord ends.

**Comment by dericed** [comment]
closing as explained in https://github.com/amiaopensource/vrecord/pull/503
