### ISSUE TITLE
analogue audio level miss match

### ISSUE THREAD

**Issue by asfinn** [amiaopensource/vrecord#438]
When passing an analogue 1K tone at -18dbfs into our vrecord workstation, vrecord -a reads this as -22.97
Our scope on the decklink SDI embedded output monitors -18dbFS and any files recorded seem to have the tone at -18dbFS so I'm confused about the vrecord reading... Does vrecord sample this after or before the Desktop Video Setup gain control?

**Comment by privatezero** [comment]
Thank you for reporting this! As a first step, would you mind testing the same command using the branch from [this pull request](https://github.com/amiaopensource/vrecord/pull/437)?

Vrecord used to have a problem with levels being slightly lower than the input source, depending on certain factors in the input signal. This was caused by some of the filtering used to construct the audio track arrangements, and was fixed a couple years ago. In putting together that recent pull request, I noticed that audio passthrough was still using the old syntax for filtering in terms of what it was using to construct the audio bars. In that pull request I brought the filter more in line with how things are done in the actual file creation in vrecord now, so it is _possible_ that this is the source of the discrepancy. Could be unrelated, but I think it is worth a check!

**Comment by bturkus** [comment]
this appears resolved to me in 2019-07-22. @asfinn could you confirm and close the issue? thanks again @privatezero!

<img width="1209" alt="Screen Shot 2019-08-02 at 9 43 18 AM" src="https://user-images.githubusercontent.com/8987230/62374470-0930bc00-b50a-11e9-9c20-cd3ae65ce21a.png">

**Comment by asfinn** [comment]
Hi - Thanks for working on this.. I can confirm with the latest vrecord 2019-07-22 there is no audio level missmatch shown in vrecord -a in our chain...  thankyou!
