### ISSUE TITLE
optional dependencies for macOS builds

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#577]
Hi,

Recently I was attempting to install the latest vrecord on a Mid 2010 Mac Pro Tower with an end-of-life operating system of High Sierra (10.13), and I discovered that some of vrecord's dependencies require Mojave (10.14) or later. Specifically, in this case it was MKVToolnix that prevented the build from completing successfully. 

This got me wondering: would it possible for us to implement a logic similar to the one in place for Linux systems, and make some of vrecord's dependencies optional for macOS? I think this would build on some of excellent work being done to bring back bmdtools, which together will allow us to reach all kinds of users who are stuck on older hardware.

Thanks for considering this. I of course don't know how to make this contribution on my own, but I'll enthusiastically cheer on anyone who can!

Ben

**Comment by retokromer** [comment]
If “only” `MKVToolnix` is blocking, then it can be installed without using Homebrew. Alternatively we could host an alternate formula for it. The same did happen many months ago with a Linux distribution – Debian if I recall carefully – and with an alternate formula applying a patch it worked like a charm, until the problem was fixed upstream.

(Also other pieces of software the community uses are “too” dependent from external behaviour. For example, you have to compile `AEO-Light` yourself on old macOS/OS X because otherwise the GPU is ignored and the software turns very longtime before ending up with an empty file.)

@bturkus Is  it “only” `MKVToolnix` that blocks?

**Comment by tomackroyd** [comment]
I am in the same boat, needing to run vrecord in macOS Sierra 10.12.6. `mkvtoolnix: macOS Mojave or newer is required.` 
Thanks Reto for opening amaios#258. In the meantime how can one install vrecord not using Homebrew? (Am currently running a version from 2019-11-14)
Tom

**Comment by dericed** [comment]
Hi @tomackroyd, you skip installing mkvtoolnix, try `brew install --ignore-dependencies vrecord`. vrecord will still work without mkvtoolnix but would skip any step to embed logs or attachments in recorded matroska after the capture.

**Comment by tomackroyd** [comment]
Hi @dericed `--ignore-dependencies` flag is rejected as invalid by Homebrew.

**Comment by retokromer** [comment]
No, `--ignore-dependencies` should nor work neither with the install nor upgrade brew option, because that would essentially be a synonyme of `--break-my-system`… If I am not totally wrong, it works only with the uninstall option, where it makes sense.

I will test if the standard `MKVToolNix` installation (I mean not via Homebrew) makes the trick; I guess on Tuesday I will have again access to old machines.

**Comment by retokromer** [comment]
Apparently, `MKFToolNix` needs now [C++17](https://github.com/Homebrew/homebrew-core/blob/69241dbc1fa89d050b8eefceb9062ddadb65f796/Formula/mkvtoolnix.rb#L34).

**Comment by retokromer** [comment]
Yes, since version 47, since 2020-05-30:

>MKVToolNix now requires a C++ compiler & standard library that support the
>following features of the C++17 standard: "`std::variant`", "`std::gcd`".
>For the GNU Compiler Collection (gcc) this means v7 or newer; for clang it
>means v4 or newer — the same versions required by earlier MKVToolNix
>versions.

**Comment by dericed** [comment]
Closing as this was addressed via https://github.com/amiaopensource/homebrew-amiaos/pull/259. If anyone has the same trouble, please reopen.
