### ISSUE TITLE
Enable Frame MD5s 

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#6]
Frame MD5s are not currently be generated. 
Maybe have this as an option in the future.

**Comment by henryborchers** [comment]
I've heard of this feature but I'm honestly curious to how this could be used.

**Comment by henryborchers** [comment]
oops. Didn't mean to close this.

**Comment by dericed** [comment]
@henryborchers wants it closed, it shall be closed

**Comment by henryborchers** [comment]
While I'm not sold on the usefulness of frame-based hashing, (outside of image-sequences), I'm curious about this. 

Wouldn't this be rather risky to calculate hashes during capture-time? I'm not the expert in this but unless you could offload the hashing calculation to something dedicated, such as a GPU, I'd be afraid of buffer-overflow.

**Comment by jfarbowitz** [comment]
Creating the frame MD5 file has been enabled again. Just need to add the option to the GUI.

**Comment by dericed** [comment]
for ref: https://github.com/amiaopensource/vrecord/commit/f4606c119ab2c95cfb0b83d5b8826e062599b4d3

**Comment by dericed** [comment]
@henryborchers we've got a few instances (couple out of millions of frames) of errors in the encoding so that the encoding does not equal the data sent to the encoder, so the framemd5s from the original encoding would give us a way to validate that and avoid issues like https://twitter.com/dericed/status/482195897456275457. This obviously needs benchmarking to figure out if its safe to run by default. Suggestions for tests?

**Comment by dericed** [comment]
the benchmarking/test question is also relevant as I'd like to consider writing a qctools report during the capture as well

**Comment by henryborchers** [comment]
Ah, I didn't think of it in that context. That makes sense. Thanks for answering my seemingly patronizing question. :-)

**Comment by jfarbowitz** [comment]
@henryborchers, what a #framemd5hater

**Comment by jfarbowitz** [comment]
should be closed as of  861e61f
