### ISSUE TITLE
big sur/gtkdialog issue

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#642]
hi,
we've upgraded a computer to macOd Big Sur, and we're experiencing an issue in which vrecord quits every time we try to select a recording directory destination. It appears to be something related to gtkdialog, but we're not getting much in the way of error reporting.

thanks in advance for any help!

Ben

**Comment by retokromer** [comment]
@bturkus On which CPU are you? Intel or ARM64? To my knowledge, except the patch we have in the formula, the `gtkdialog` code we use is from 2013-01-06, i.e. almost 8 years old. I’ll try to take a look, but not in the next days.

**Comment by bturkus** [comment]
hi @retokromer we're trying this on a newly upgraded 2013 trash can, so Intel I believe?

**Comment by retokromer** [comment]
@bturkus Yep, that’s Intel. Thank you for the quick answer!

**Comment by privatezero** [comment]
Hi @bturkus, not sure if I'll be able to recreate as I only have access to macOS 10.15, but how exactly does the GUI quit? Is it when you click the button to select a recording directory? When you click the button to save the recording directory? Does running vrecord with `bash -x vrecord -e` give any useful output about the last thing to happen before the crash? (I'm guessing `bash -x` won't help as the problem is probably related to the gtkdialog sub shell processes, but worth a shot maybe)

**Comment by kieranjol** [comment]
I can replicate this on Intel big sur - it also happens when you try to select the auxiliary directory. Specifically, when you click either of these options, nothing happens, and when you click again, you get the crash. here's the last few lines before the crash with `-x`
My bash is rusty but I'd imagine that the issue is the blank `eval ''`?

```
+ GTK_INC=/tmp/vrecord.XNiTQI.vrecord.gtkdialog.inc
+ cat /tmp/v_vrecord_variables.txt
+ echo CONFIG_FILE=/Users/kieranjol/.vrecord.conf
+ cat /usr/local/opt/vrecord/vrecord_functions
+ [[ '' = \Y ]]
+ [[ edit = \G\U\I ]]
+ [[ '' = \1 ]]
++ gtkdialog --include=/tmp/vrecord.XNiTQI.vrecord.gtkdialog.inc --program MAIN_DIALOG --center
+ eval ''

```
[snip]

```
    <variable>MAIN_DIALOG</variable>
    <action signal="show" type="refresh">VRECORD_FORM_VALIDATION</action>
    <action signal="enter-notify-event" type="refresh">VRECORD_FORM_VALIDATION</action>
    <action signal="leave-notify-event" type="refresh">VRECORD_FORM_VALIDATION</action>
    <action signal="show" type="closewindow">HOME_DIALOG</action>
    <action signal="show" type="refresh">VRECORD_OUTPUT_NAME</action>
    <action signal="show" condition="command_is_true( [[ \"$AUDIO_DEV_CHOICE\" != *\"Blackmagic\"* ]] && echo true)">enable:AUDIO_MODE_SR_CHOICE</action>
    <action signal="show" condition="command_is_true( [[ \"$AUDIO_DEV_CHOICE\" == *\"Blackmagic\"* ]] && echo true)">disable:AUDIO_MODE_SR_CHOICE</action>
</window>
'
+ [[ '' = \a\b\o\r\t ]]
+ [[ '' = \C\a\n\c\e\l ]]
+ [[ '' = \R\e\c\o\r\d ]]
+ [[ '' = \p\a\s\s\t\h\r\o\u\g\h ]]
+ [[ '' = \r\e\f\r\e\s\h ]]
+ [[ '' = \t\i\m\e\c\o\d\e\_\s\c\a\n ]]
+ _report_unexpected_error EXIT
+ ERROR_VAR_NAME=EXIT
+ ERROR_VAR_VALUE=
+ shift
+ ERROR_DETAIL=("${@}")
+ _report -d -wt 'vrecord exited a form in an unexpected way (EXIT=), please report this error to https://github.com/amiaopensource/vrecord/issues'
++ tput setaf 1
+ local 'RED='
++ tput setaf 2
+ local 'GREEN='
++ tput setaf 4
+ local 'BLUE='
++ tput sgr0
+ local 'NC='
+ local COLOR=
+ local STARTMESSAGE=
+ local ECHOOPT=
+ OPTIND=1
+ getopts qdwstn opt
+ case "${opt}" in
+ COLOR=''
+ getopts qdwstn opt
+ case "${opt}" in
+ COLOR=''
+ getopts qdwstn opt
+ case "${opt}" in
+ STARTMESSAGE+=($(_get_iso8601) '- ')
++ _get_iso8601
++ date +%FT%T
+ getopts qdwstn opt
+ shift 2
+ MESSAGE='vrecord exited a form in an unexpected way (EXIT=), please report this error to https://github.com/amiaopensource/vrecord/issues'
+ echo '' 2020-12-07T19:31:13 '- vrecord exited a form in an unexpected way (EXIT=), please report this error to https://github.com/amiaopensource/vrecord/issues'
 2020-12-07T19:31:13 - vrecord exited a form in an unexpected way (EXIT=), please report this error to https://github.com/amiaopensource/vrecord/issues
+ [[ -n '' ]]
+ [[ -f '' ]]
+ exit 1
```

**Comment by dericed** [comment]
The `eval=''` is when the bash script is processing the output of gtkdialog, which is ordinarily a list of `key=variable` so those are set for the rest of the script. Since gtk crashes here, there is no output for eval to process.

I am testing this on big sur as well, but can't recreate the issue (works for me). Can you share your ~/.vrecord.conf file. Or try to run again with `./vrecord -G -e` and see if -G gives better clues.

**Comment by bturkus** [comment]
this is working for me now too! (vrecord 10-21 + trash can + desktop video 11.7). I think I can close and we can consolidate some of these big sur issues?

**Comment by privatezero** [comment]
Glad to hear it works! Working on my end as well! I'd say go ahead and close

**Comment by bturkus** [comment]
this is bringing me joy
