### ISSUE TITLE
audio capture mode sampling rate grayed out

### ISSUE THREAD

**Issue by bturkus** [amiaopensource/vrecord#693]
Hi,

We might be missing something here, but on the latest vrecord (09-03), on macOS Big Sur, we're finding that we can't select between the three audio sampling rates on offer when using Audio Capture mode. It seems to be defaulting to 48 kHz, and clicking around we can't find a way to enable the other options (but switching inputs from Blackmagic to the iMac microphone does seem to reenable the selection).

Thanks for looking into this!

Ben

**Comment by privatezero** [comment]
Hi Ben,

This is intentional - the Blackmagic FFmpeg device is locked to 48 kHz (as is the Blackmagic hardware itself - right?) so if you are using a Blackmagic device then the GUI won't give you an option to select a sample rate as we don't want people to have any false impressions that their choices are doing anything.

Any suggestions to make that more clear? Maybe a bit of explanation within the menu itself that 48 is locked in?

**Comment by bturkus** [comment]
Oh, that makes a lot of sense, thanks for the clarification. I think when I was testing audio mode in the past, I was using a audiocassette deck and an audio a-d, so I never fully appreciated that we were locking in BM devices at 48 (which does seem like the right thing to do; for some reason I thought we might be allowing people to pointlessly up-sample).

The reason we were interested in other sampling rates is that we encounter a fair amount of PCM F1 tapes, and I thought there might be some way to cheat the BM locked-in rate and capture to closer to the 44.1 that's common on these tapes, without having to adjust our set-ups. Clearly the better way to do this is to use a dedicated audio a-d, but again happy to finally understand what is and is not possible.

Regarding conveying this to vrecord users, I think a menu explanation would be really handy.

Thanks again!

**Comment by bturkus** [comment]
and closing now...
