### ISSUE TITLE
Inconsistencies with Preview button

### ISSUE THREAD

**Issue by privatezero** [amiaopensource/vrecord#705]
When vrecord GUI is launched via `vrecord` the Preview button will instead launch record mode and prompt for input. Order of conditionals and functions around [line 2240](https://github.com/amiaopensource/vrecord/blob/main/vrecord#L2240) needs some tweaking.

**Comment by libbyhopfauf** [comment]
@privatezero I was just about to post separately about this (but it's an older issue that I've been meaning to create an issue for a bit), but maybe it's related? If not, I can create a new issue:

At MIPoPS all of our computers have a shell script to launch the vrecord GUI (literally just `vrecord -g`) but recently each one had to be changed to vrecord -e to just launch the edit mode instead of the previous set of 6 buttons. If `vrecord -g` is run manually in the terminal,  I get "bad option":

<img width="882" alt="Screen Shot 2022-02-01 at 2 43 56 PM" src="https://user-images.githubusercontent.com/13877631/152063990-0907a608-fab2-4ab1-8643-5f678eefde8c.png">
