### ISSUE TITLE
EXIT=audiopassthrough

### ISSUE THREAD

**Issue by jbbenoit73** [amiaopensource/vrecord#709]
Hello,
I have got 2 issues.
First : in the vrecord audio tab, the "audio device" column is empty while there are two audio cards.
Second : in the home menu, when i load "Audio Check" Vrecord exits and sends the message 
"numerisation@numerisation:~$ vrecord -e
 2022-02-02T10:18:10 - vrecord exited a form in an unexpected way (EXIT=audiopassthrough), please report this error to https://github.com/amiaopensource/vrecord/issues
numerisation@numerisation:~$ "
My system is Ubuntu.20.04 in a Precision Dell Tower with an Bmd Intensity Pro 4K B inside.
Thanks for help,
JB B

**Comment by privatezero** [comment]
Hi @jbbenoit73 - thanks for reporting this! I think I've figured out the [glitch causing the button problem](https://github.com/amiaopensource/vrecord/pull/710).

When I get a chance I'll take a deeper look to see if I can notice anything that might be creating errors with the device list.

**Comment by privatezero** [comment]
@jbbenoit73 - vrecord relies on parsing the output of arecord to populate the list of audio devices on Linux. Could you tell me what the output of `arecord -l` is on your end?

arecord should come installed as part of the system, but if for some reason you don't have it, try installing with `sudo apt install alsa-utils`

**Comment by privatezero** [comment]
@jbbenoit73 thanks for providing that output, that was very helpful! The problem was the underlying function for populating that list was incorrectly assuming an English output from `arecord`.

We have a patch at https://github.com/amiaopensource/vrecord/pull/713 that will fix this, so should be resolved soon!

**Comment by jbbenoit73** [comment]
@privatezero Thanks you. 
I tried vrecord by changing the system language settings, it works but I have to go back to the french settings.
Sorry, I'm not a computer scientist, can you tell me how to use the patch? I guess that i have to correct a 'vrecord' file but which one?
Regards. jb

**Comment by privatezero** [comment]
I'm hoping we can get this fix merged into a new release in the next couple of days, so at that point all you will need to do is update vrecord with `brew update && brew upgrade vrecord` (assuming you used homebrew to install vrecord) to get the fixes.

In the meantime, if you are in a hurry you can download the branch of vrecord that includes the fix [here](https://github.com/amiaopensource/vrecord/archive/refs/heads/expand-language-support.zip) and then run it directly from that folder by opening that folder in the terminal and making sure to always use `./vrecord` instead of `vrecord` to run the command.

**Comment by jbbenoit73** [comment]
Thank you very much.
jb

**Comment by privatezero** [comment]
Closing as should be fixed in https://github.com/amiaopensource/vrecord/pull/714
