### ISSUE TITLE
MKV Video Failing MediaConch GUI Ex. policy

### ISSUE THREAD

**Issue by SoFrans** [amiaopensource/vrecord#857]
Hi,

I was wondering if anyone has run into this problem as well. When I put a MKV file that was generated with VRecord into MediaConch to run the report  (Example MKV FFV1 digitization policy), it fails. The point of failure is the Display Aspect Ratio, MediaConch wants it to be 4/3, however the actual value that is being reported is 1.347 (I have 4:3 selected in VRecord). I know that this is negligible, but is there a way to get a true 4:3 so it doesn't fail the policy check?

Thanks, 
Sophia

**Comment by SoFrans** [comment]
Also apparently the access files are getting a display aspect ratio of 3:2 and that doesn't seem right to me... 
(sorry we are switching from uncompressed to FFV1 native capture so I'm being very careful with the transition).

**Comment by dericed** [comment]
Hi @SoFrans, this issue was fixed in https://github.com/amiaopensource/vrecord/commit/5b9fa8b3ddf7e040e353cb1c4f4d4fd1962b07ea. We had added some fine-tuning for display aspect ratio but forgot to support that in the mediaconch test. I think if you update vrecord, you'll find the issue resolved. The 3:2 DAR issue sounds unexpected though, was the access file made by vrecord?

**Comment by SoFrans** [comment]
Hi Dave, 

The access file was made in VRecord. I have multiple that seem to be showing that 3:2 DAR for the access copies. Happy to share the MediaInfo report with you if need be.

So the display aspect ratio bit for FFV1 even though it is failing in the MediaConch GUI is fine? If so great.

Thanks, 
Sophia

**Comment by SoFrans** [comment]
I just checked and the height and width of the video is what it should be, but for whatever reason the DAR is wrong...

**Comment by dericed** [comment]
can you send along the ffmpeg log for this capture?

Also see this discussion for the background on vrecord changing it's approach to aspect ratio: https://github.com/amiaopensource/vrecord/issues/689

**Comment by dericed** [comment]
Hi @SoFrans, I'm realizing that to fix this issue we'd need to adjust Mediaconch rather than vrecord. The mediaconch policy that is stored within vrecord is already updated for this but a similar one in Mediaconch is not. That lives at https://github.com/MediaArea/MediaConch_SourceCode/blob/b0b89e4a6e61f2c4dc1df935e668296f558a5f7f/Tools/Policies/sample_policy_4_output.xml#L13.

I'm considering how to update that as either we could:
- remove the test there altogether
- update it to test for a range of display aspect ratio range than just 1.333. Like maybe 1.316...1.350 since that's the range covered by the options now in vrecord for 4/3.

**Comment by dericed** [comment]
Hi @SoFrans this is partly fixed in https://github.com/MediaArea/MediaConch_SourceCode/pull/791. Here the example MediaConch policy you mentioned is updated to consider the range used for 4/3 video vrecord. The other issue you mentioned about the aspect ratio of the mp4 is addressed in https://github.com/amiaopensource/vrecord/pull/858 but some comments are needed there.

**Comment by dericed** [comment]
will close as this is fixed in https://github.com/amiaopensource/vrecord/pull/858 and https://github.com/MediaArea/MediaConch_SourceCode/pull/791. Thanks @SoFrans, this should all work in the next releases of MediaConch and Vrecord.
