### ISSUE TITLE
Possible to include Pashua in Brew formula?

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/vrecord#94]
I had to seek out an internet connection to do an installation of vrecord. But then when I tried to run it I realized I needed an internet connection again to install Pashua. It would be nice if all the required components were installed on one go. It would be especially helpful if implementing vrecord in areas that do not have good internet access.

Is it possible to add Pashua as a dependency to the homebrew formula for vrecord? Is there a specific reason why that hasn't been done before?

**Comment by dericed** [comment]
when I tried this initially it wasn't possible (or at least I couldn't figure out how) to add a `depends_on` in the installer to a cask installer.

**Comment by retokromer** [comment]
The same question came up to me too (also in another script). I will check if the `depends_on` may be added in the cask installer.

**Comment by retokromer** [comment]
Sorry, I haven't found an elegant way to include it.

**Comment by privatezero** [comment]
Since the creator of Pashua [gives permission](https://www.bluem.net/pashua-docs-latest.html#faq.redistribution) to include it with non-commercial open source software and since so much of vrecord's functionality is built on it, would it be worth including Pashua as part of the repository?

Then we could change the homebrew install file to move it to Applications by including something like:

```
  def post_install;
    system `pashua_path=$(find /usr/local/Cellar/vrecord/ -iname Pashua.app) && echo "mv $pashua_path /Applications/Pashua.app"`
  end
```

Tested this out with a different repo-not particularly elegant, but it works!

**Comment by retokromer** [comment]
Fine with me.

**Comment by privatezero** [comment]
This should take care of the issue without having to include Pashua in the repo. https://github.com/amiaopensource/homebrew-amiaos/pull/13

**Comment by privatezero** [comment]
Gonna close this as the changed formula has been merged!
